#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd, using the while loop + IFS
IFS=''
while IFS=: read -r username password userid groupid gecos homedir shell
do
      echo "The user $f1 is part of the $f3, lives in $6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here:$f5"
done < /etc/passwd 
