#!/usr/bin/env bash
#script that groups visitors by IP and HTTP status code, and displays this data.
awk '{print $6}' combined_log | sort | uniq -c | sort -fr | awk '{print $1,$9}' | sort | uniq -c | sort -fr  
