#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes
hour=0
while [ $hour -lt 12 ]
do
       echo "Hour: $hour"
       minute=1
       while [ $minute -lt 59 ]
       do
              echo "$minute"
              ((minute++ ))
       done
       ((hour++ ))
       head -n 70
done
