#!/usr/bin/env bash
#script that creates the file /var/run/myscript.pid containing its PID
script="/var/run/myscript.pid"
echo $$ > "$script"
trap 'echo "I hate the kill command"; rm "$script"; exit' SIGTERM SIGQUIT
while true;
do 
   echo "To infinity and beyond"
done
