#!/usr/bin/env bash
#script that creates the file /var/run/myscript.pid containing its PID
file=var/run/myscript.pid
echo $$ > "$file"
trap 'echo "I hate the kill command"' 15
while true;
do 
   echo "To infinity and beyond"
done
