#!/usr/bin/env bash
#script that creates the file /var/run/myscript.pid containing its PID
$ echo $$ > var/run/myscript.pid
trap 'echo "I hate the kill command"' 15
while true ;
do 
   echo "To infinity and beyond"
done


